version: '3'

volumes:
  dados:


services:

  db:
    image: postgres
    #restart: always
    volumes:
      #Volume dos dados
      - dados:/var/lib/postgresql/data
      #Volume Scripts
      # Mapeando a pasta scripts daqui, para a pasta scripts dentro do container
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      #Site
      - ./web:/usr/share/nginx/html
      # Configuração do Proxy Reverso
      # Interessante pois substitui as configurações padrão do nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
  app:
    image: python:3.6
    volumes:
      #Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080