version: '3'

volumes:
  dados:


services:
  db:
    image: postgres:9.6
    volumes:
      #Volume dos dados
      - dados:/var/lib/postgresql/data
      #Volume Scripts
      # Mapeando a pasta scripts daqui, para a pasta scripts dentro do container
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      #Site
      - ./web:/usr/share/nginx/html
    ports: 
      - 80:80
    